const races = [
    {
        image: 'races/human.webp',
        title: 'Human',
        description: 'Humans are the most adaptable and ambitious of the common races. They thrive in every corner of the world, from bustling cities to remote villages. Unlike other races, humans lack a singular defining trait or culture, which is their greatest strength. They embody a wide range of alignments, values, and ambitions. Humans are short-lived compared to many races, usually living to about 80 years, which drives their intense desire to achieve greatness in their lifetimes. They excel at innovation and exploration, often leading the charge into the unknown or spearheading societal advancements.',
        smtitle: '',
        smdescription: 'Humans possess a diverse array of cultures, languages, and traditions depending on the region they hail from. This diversity makes them a unifying or divisive force in the realms they inhabit. As adventurers, humans can be anything from noble paladins to cunning rogues, showcasing their versatility. Their ability to adapt to any environment makes them natural diplomats, leaders, and pioneers.',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/elf.webp',
        title: 'Elf',
        description: '',
        smtitle: 'High Elf',
        smdescription: 'High Elves are among the most refined and intellectual of the Elven subraces. With lifespans that span centuries, they are often deeply immersed in the study of magic, philosophy, and art. Their lands are magnificent, filled with towering spires and shimmering forests, showcasing their advanced knowledge and connection to the arcane. High Elves tend to see themselves as guardians of magical traditions and often view other races with a mix of curiosity and condescension.',
        smtitle1: 'Wood Elf',
        smdescription1: 'Wood Elves are the protectors of the forests, blending seamlessly with the natural world. They are agile and attuned to nature, often acting as rangers, druids, or scouts. Unlike their High Elf cousins, they eschew grandeur and sophistication in favor of simplicity and balance. Their villages are often hidden among the trees, ensuring they can guard their lands from threats while maintaining harmony with the wilderness.',
        smtitle2: 'Dark Elf/Drow',
        smdescription2: 'The Drow are a subrace of Elves who dwell in the shadowy depths of the Underdark. Known for their dark skin, white hair, and innate connection to magic, they are as feared as they are fascinating. Drow society is matriarchal and often ruthless, ruled by powerful priestesses of Lolth, the Spider Queen. While many Drow are aligned with evil, some strive to escape their societys tyranny and seek redemption on the surface.',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/dwarf.webp',
        title: 'Dwarf',
        description: '',
        smtitle: 'Hill Dwarf',
        smdescription: 'Hill Dwarves are the steadfast and wise branch of the Dwarven people. Known for their resilience and strong constitutions, they excel as craftsmen, warriors, and clerics. Hill Dwarves live in expansive mountain halls or underground strongholds, where they mine precious metals and gemstones. Their society values tradition and family, and they often serve as the keepers of ancient lore and traditions.',
        smtitle1: 'Mountain Dwarf',
        smdescription1: 'Mountain Dwarves are the hardiest and most warlike of their kind. Taller and broader than Hill Dwarves, they are natural-born warriors and smiths, excelling in heavy armor and melee combat. Their strongholds are fortified bastions, often carved directly into the peaks of mountains. Mountain Dwarves value honor and discipline, making them fierce allies and formidable foes.',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/halfling.webp',
        title: 'Halfling',
        description: '',
        smtitle: 'Lightfoot Halfling',
        smdescription: 'Lightfoot Halflings are the adventurous and charismatic subrace of Halflings. They are often found traveling in caravans or living among other races. Their natural stealth and ability to blend into crowds make them excellent spies, rogues, or bards. Despite their wanderlust, Lightfoots are known for their close-knit families and cheerful dispositions.',
        smtitle1: 'Stout Halfling',
        smdescription1: 'Stout Halflings are the tougher, more grounded counterparts to the Lightfoot. They have a natural resistance to poison and a heartier constitution, making them ideal adventurers in dangerous environments. They prefer simpler, quieter lives in rural communities but are always ready to defend their homes and loved ones with courage.',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/half-elf.webp',
        title: 'Half-Elf',
        description: 'Half-Elves are the offspring of humans and elves, embodying the best traits of both races. They inherit their Elven parents beauty, grace, and longevity while gaining the adaptability and ambition of their Human lineage. Often caught between two worlds, Half-Elves are natural diplomats and adventurers. They possess an innate charm and empathy that allows them to navigate various cultures with ease. Half-Elves excel in versatility, often taking on roles that require both finesse and resilience.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/half-orc.webp',
        title: 'Half-Orc',
        description: 'Half-Orcs are the result of unions between humans and orcs, often in turbulent circumstances. They are strong, resilient, and fiercely determined, inheriting the ferocity of their Orc parent and the resourcefulness of their Human heritage. Many Half-Orcs struggle to find acceptance in either culture, which makes them naturally self-reliant and driven. Their physical prowess and intimidating presence make them excellent fighters, barbarians, and warlords.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/gnome.webp',
        title: 'Gnome',
        description: '',
        smtitle: 'Forest Gnome',
        smdescription: 'Forest Gnomes are whimsical and reclusive, living in harmony with nature. They have a knack for illusion magic and an inherent connection to animals. Forest Gnomes often reside in hidden glades or burrows, far from prying eyes, and are known for their mischievous sense of humor and boundless creativity.',
        smtitle1: 'Rock Gnome',
        smdescription1: 'Rock Gnomes are the inventors and tinkerers of the Gnome race. They are naturally curious and brilliant, creating ingenious devices and contraptions. Their homes are bustling workshops filled with gadgets and experiments. Rock Gnomes love puzzles, challenges, and the pursuit of knowledge, making them exceptional artificers and scholars.',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/tiefling.webp',
        title: 'Tiefling',
        description: 'Tieflings are a race touched by infernal bloodlines, often descending from humans who made pacts with devils. Their appearance—characterized by horns, tails, and vibrant skin tones—marks them as different, often invoking fear or prejudice. Despite this, Tieflings are fiercely independent and determined to define their own destinies. Their natural charisma and affinity for magic make them excellent sorcerers, warlocks, or bards. Tieflings often grapple with their infernal heritage, choosing paths of redemption, rebellion, or acceptance.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/aasimar.webp',
        title: 'Aasimar',
        description: '',
        smtitle: 'Protector Aasimar',
        smdescription: 'Protector Aasimar are divine beings blessed with celestial guidance. They are guardians of the weak and champions of justice, often radiating an aura of purity. These Aasimar are known for their ability to sprout radiant wings, enabling flight and enhancing their combat abilities. They gravitate towards roles like clerics or paladins, striving to uphold virtue wherever they go. Their connection to divine power makes them inspiring leaders and fearsome protectors.',
        smtitle1: 'Scourge Aasimar',
        smdescription1: 'Scourge Aasimar are celestial warriors who embody righteous fury. They are driven by an inner flame that punishes corruption and darkness. Their radiant energy is a double-edged sword, capable of dealing immense damage to foes but also causing personal harm. Scourge Aasimar are relentless in their pursuit of justice, often pushing themselves to dangerous limits to ensure the triumph of good.',
        smtitle2: 'Fallen Aasimar',
        smdescription2: 'Fallen Aasimar have strayed from their celestial origins, often due to trauma, corruption, or personal choice. These beings grapple with inner conflict, balancing their inherent goodness with the dark forces that now define them. Their once-radiant features have taken on a more haunting appearance, and they exude a frightening, necrotic aura. Fallen Aasimar often pursue paths of redemption or vengeance, making them intriguing antiheroes.',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/genasi.webp',
        title: 'Genasi',
        description: '',
        smtitle: 'Air Genasi',
        smdescription: 'Air Genasi are descendants of air elementals, known for their lightness and agility. They have features reminiscent of the wind, such as breezy hair or translucent skin. These individuals are free-spirited and quick-thinking, thriving as adventurers who enjoy exploration. Air Genasi excel as rogues, monks, or sorcerers.',
        smtitle1: 'Earth Genasi',
        smdescription1: 'Earth Genasi are sturdy and unyielding, often resembling stone or mineral. They are descendants of earth elementals and possess unparalleled resilience. Their skin may glitter like quartz or have the texture of rough stone. Earth Genasi are dependable and strong, making them ideal fighters or barbarians.',
        smtitle2: 'Fire Genasi',
        smdescription2: 'Fire Genasi are passionate and fierce, their lineage tied to fire elementals. Flames often flicker in their hair or smolder in their eyes. They are quick-tempered and ambitious, often taking on roles as sorcerers or warlocks. Fire Genasi possess an innate resistance to fire, which makes them well-suited for combat in dangerous environments.',
        smtitle3: 'Water Genasi',
        smdescription3: 'Water Genasi are graceful and fluid, with features that echo the ocean. Their skin may shimmer like water, and they often leave droplets behind. Water Genasi excel as druids or clerics, using their natural connection to the sea to guide their allies. They are calm yet powerful, embodying the duality of water’s gentle and destructive nature.',
    },
    {
        image: 'races/goliath.webp',
        title: 'Goliath',
        description: 'Goliaths are mountain-dwelling giants known for their immense strength and endurance. Their gray, stony skin and towering frames make them imposing figures. Goliaths are highly competitive, valuing self-improvement and personal achievement. They thrive in harsh environments, where their survival skills and physical prowess shine. Goliaths often excel as barbarians or fighters, using their natural might to protect their communities or explore uncharted lands.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/firbolg.webp',
        title: 'Firbolg',
        description: 'Firbolgs are gentle giants with an intrinsic connection to nature. They dwell in secluded forests, living in harmony with the wilderness. Firbolgs are known for their wisdom and magical affinity, often serving as druids or rangers. Their serene demeanor hides immense strength, making them capable defenders of their homes. Firbolgs possess unique abilities, such as speaking to plants and animals, which deepen their bond with the natural world.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/triton.webp',
        title: 'Triton',
        description: 'Tritons are aquatic humanoids from the deep seas, known for their noble demeanor and sense of duty. They are protectors of the ocean and its inhabitants, often venturing to the surface to combat threats. Tritons have vibrant, fish-like features and excel as paladins, clerics, or druids. Their affinity for water magic and their selfless nature make them valuable allies.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/tabaxi.webp',
        title: 'Tabaxi',
        description: 'Tabaxi are feline humanoids driven by curiosity and wanderlust. They hail from tropical jungles, but their adventurous spirit often leads them far from home. Tabaxi are agile, perceptive, and resourceful, making them excellent rogues or monks. They are collectors of stories, artifacts, and secrets, always seeking new experiences and knowledge.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/lizardfolk.webp',
        title: 'Lizardfolk',
        description: 'Lizardfolk are cold-blooded reptilian humanoids with a pragmatic and survivalist outlook. They inhabit swamps, jungles, and other wet environments, using their natural adaptability to thrive. Lizardfolk are skilled hunters and craftsmen, creating tools from natural materials. Their lack of emotional attachment can make them seem distant, but their loyalty to their tribes is unwavering.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/kenku.webp',
        title: 'Kenku',
        description: 'Kenku are bird-like humanoids cursed with the inability to speak their own words or fly. Instead, they mimic the voices and sounds they hear. Kenku are crafty and resourceful, often excelling as rogues or bards. Their unique communication and cunning make them mysterious and unpredictable allies.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/tortle.webp',
        title: 'Tortle',
        description: 'Tortles are turtle-like humanoids known for their wisdom and peaceful nature. They have a strong connection to the land and often take on the role of nomadic sages or druids. Tortles carry their homes on their backs, which reflects their self-reliant and contemplative lifestyle.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/hobgoblin.webp',
        title: 'Hobgoblin',
        description: 'Hobgoblins are militaristic and disciplined goblinoids with a strong sense of honor and loyalty. They often serve as strategists and soldiers in large armies. Hobgoblins excel as fighters or warlords, leading their kin to glory on the battlefield.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/bugbear.webp',
        title: 'Bugbear',
        description: 'Bugbears are large, brutish goblinoids with exceptional strength and stealth. They are often mercenaries or bandits, using their physical prowess to intimidate others. Despite their fearsome reputation, Bugbears value camaraderie and teamwork within their groups.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/goblin.webp',
        title: 'Goblin',
        description: 'Goblins are small, cunning creatures known for their resourcefulness and trickery. They thrive in chaos and often inhabit caves, ruins, or ramshackle settlements. Goblins excel as rogues or tinkers, using their ingenuity to survive.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/kobold.webp',
        title: 'Kobold',
        description: 'Kobolds are diminutive, dragon-like humanoids who revere dragons as their ancestors. They are excellent trap-makers and miners, often dwelling in elaborate underground tunnels. Despite their small stature, Kobolds are fierce defenders of their homes and kin.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/yuan-ti_pureblood.webp',
        title: 'Yuan-ti Pureblood',
        description: 'Yuan-ti Purebloods are serpentine humanoids descended from an ancient, magically altered lineage. They are cunning and manipulative, often serving as spies or sorcerers. Yuan-ti Purebloods are known for their ambition and innate magical abilities.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/orc.webp',
        title: 'Orc',
        description: 'Orcs are powerful, warlike humanoids who value strength and bravery above all. They are often seen as fierce raiders, but some seek redemption or a life beyond violence. Orcs excel as barbarians or fighters, using their physical might to protect or conquer.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/gith.webp',
        title: 'Gith',
        description: '',
        smtitle: 'Githyanki',
        smdescription: 'Githyanki are warriors from the Astral Plane, known for their martial prowess and connection to psionics. They are fierce and disciplined, often raiding the Material Plane for resources.',
        smtitle1: 'Githzerai',
        smdescription1: 'Githzerai are ascetic monks who dwell in the chaotic Limbo. They seek enlightenment and discipline, using their psionic abilities to maintain order within their realm.',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/changeling.webp',
        title: 'Changeling',
        description: 'Changelings are shapeshifters with the ability to alter their appearance at will. They are enigmatic and secretive, often using their abilities to infiltrate or deceive. Changelings excel in social interactions, making them excellent spies or bards.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/shifter.webp',
        title: 'Shifter',
        description: '',
        smtitle: 'Beasthide',
        smdescription: 'Beasthide Shifters draw strength from their animalistic heritage, gaining enhanced resilience and endurance during their transformations.',
        smtitle1: 'Longtooth',
        smdescription1: 'Longtooth Shifters exhibit wolf-like traits, becoming ferocious and aggressive in combat. They excel as barbarians or rangers.',
        smtitle2: 'Swiftstride',
        smdescription2: 'Swiftstride Shifters are agile and graceful, channeling feline traits to enhance their mobility. They make excellent rogues or monks.',
        smtitle3: 'Wildhunt',
        smdescription3: 'Wildhunt Shifters are trackers and hunters, drawing on keen senses and animal instincts to excel in roles such as rangers or druids.',
    },
    {
        image: 'races/centaur.webp',
        title: 'Centaur',
        description: 'Centaurs are a blend of human and horse, embodying the wild and untamed nature of the forest and plains. Their dual form grants them speed and strength, making them exceptional warriors and scouts. Centaurs value freedom and community, often forming tight-knit clans that live in harmony with nature. They are skilled hunters and gatherers, with a deep connection to the land. Centaurs excel as rangers or druids, using their natural talents to protect their territories.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/minotaur.webp',
        title: 'Minotaur',
        description: 'Minotaurs are powerful, bull-like humanoids known for their strength and combat prowess. They often dwell in labyrinthine lairs or coastal strongholds. Minotaurs are guided by a strong sense of honor and personal achievement, often living by a strict code. While their fearsome appearance may intimidate others, Minotaurs value loyalty and bravery. They are formidable barbarians or fighters, thriving in roles that demand physical might.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/satyr.webp',
        title: 'Satyr',
        description: 'Satyrs are whimsical, goat-like humanoids who embody the spirit of revelry and freedom. They are native to enchanted forests and magical realms, thriving on music, dance, and storytelling. Satyrs possess a natural charm and an adventurous spirit, often acting as bards or rogues. Their playful nature hides a sharp wit, and they are fiercely protective of their friends and homes.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/leonin.webp',
        title: 'Leonin',
        description: 'Leonin are lion-like humanoids native to vast savannas. They are proud, noble, and fiercely independent, with a strong sense of justice. Leonin are exceptional warriors, excelling as paladins or fighters. They value strength, honor, and the bonds of their prides. Despite their aloof nature, Leonin are loyal allies who fight fiercely to protect their kin and homes.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/verdan.webp',
        title: 'Verdan',
        description: 'The Verdan are a mysterious and adaptable race born from magical transformations. They are small, green-skinned humanoids who grow in size and wisdom over time. Verdan possess an innate curiosity and a kind-hearted nature, often seeking to understand and connect with others. They are excellent diplomats or bards, using their charm and empathy to bring people together.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/simic_hybrid.webp',
        title: 'Simic Hybrid',
        description: 'Simic Hybrids are the result of magical and biological experimentation, blending humanoid traits with those of animals or other creatures. They often possess unique features like fins, claws, or wings, depending on their enhancements. Simic Hybrids are resourceful and innovative, excelling in roles like artificers or druids. Their adaptability makes them valuable allies in both combat and exploration.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/vedalken.webp',
        title: 'Vedalken',
        description: 'Vedalken are tall, blue-skinned humanoids known for their logical minds and passion for discovery. They are meticulous and curious, often dedicating their lives to the pursuit of knowledge and innovation. Vedalken are excellent artificers or wizards, using their intellect to create powerful inventions and spells. They are cooperative and thrive in environments that value intellect and creativity.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/loxodon.webp',
        title: 'Loxodon',
        description: 'Loxodons are elephant-like humanoids known for their wisdom, patience, and immense strength. They are natural protectors, often serving as clerics or paladins in their communities. Loxodons value tradition and community, striving to maintain harmony in their lives. Their imposing presence is matched by their gentle demeanor, making them both fearsome defenders and wise counselors.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/kalashtar.webp',
        title: 'Kalashtar',
        description: 'Kalashtar are humanoids bonded with spirits from the dream plane, granting them heightened psychic abilities and a serene demeanor. They are introspective and compassionate, often seeking to bring peace to a troubled world. Kalashtar excel as monks or sorcerers, using their psychic gifts to aid their allies and confront their enemies. They often carry an aura of otherworldly calm, inspiring trust in those they meet.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/warforged.webp',
        title: 'Warforged',
        description: 'Warforged are living constructs created for war but yearning for purpose beyond battle. Made of metal, wood, and stone, Warforged are resilient and tireless beings who can adapt to a variety of roles. They are deeply introspective, often grappling with questions of identity and freedom. Warforged excel as fighters or artificers, combining their innate durability with their desire for growth.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/astral_elf.webp',
        title: 'Astral Elf',
        description: 'Astral Elves are celestial beings who hail from the Astral Plane. They are timeless and wise, with a profound connection to the cosmos. Astral Elves possess radiant features and an innate affinity for magic, often excelling as wizards or clerics. They are driven by a sense of duty to preserve balance and knowledge, making them both inspiring leaders and powerful spellcasters.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/autognome.webp',
        title: 'Autognome',
        description: 'Autognomes are small, mechanical beings crafted by gnomes. They possess a whimsical charm and a knack for invention, often pursuing roles as artificers or bards. Autognomes are curious and playful, yet highly dependable. Their mechanical nature gives them resilience, making them versatile adventurers.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/hadozee.webp',
        title: 'Hadozee',
        description: 'Hadozee are monkey-like humanoids known for their agility and adventurous spirit. They are natural climbers and gliders, often taking to the rigging of ships or exploring dense jungles. Hadozee are cheerful and loyal, making them excellent companions on any journey. They thrive as rogues or rangers, using their agility to navigate treacherous terrain.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/plasmoid.webp',
        title: 'Plasmoid',
        description: 'Plasmoids are amorphous, gelatinous beings capable of shifting their forms. They are curious and adaptable, often exploring the world with childlike wonder. Plasmoids excel in creative problem-solving and can fit into tight spaces or mimic shapes. They make excellent rogues or druids, using their unique abilities to navigate challenges.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/thri_kreen.webp',
        title: 'Thri-kreen',
        description: 'Thri-kreen are insectoid humanoids with a strong sense of community and survival. They possess four arms, chitinous armor, and an innate connection to nature. Thri-kreen are hunters and gatherers, thriving in deserts and savannas. They excel as rangers or monks, using their agility and natural weapons to protect their tribes and homes. Their alien appearance and culture make them fascinating adventurers.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/fairy.webp',
        title: 'Fairy',
        description: 'Fairies are small, winged beings filled with magic and wonder. They hail from enchanted forests or the Feywild, embodying the whimsy and unpredictability of nature. Fairies often use their charm and magical abilities to explore the world or defend their homes. They make excellent sorcerers or bards, weaving spells and songs with innate grace. Despite their small stature, Fairies are resourceful adventurers.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/harengon.webp',
        title: 'Harengon (Rabbitfolk)',
        description: 'Harengons are rabbit-like humanoids native to lively meadows and peaceful forests. Known for their agility and sharp instincts, Harengons are excellent at avoiding danger and leaping into action. They often thrive as monks or rogues, using their quick reflexes and resourcefulness. Harengons are cheerful and social, bringing a sense of playfulness and optimism to their parties.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/ardlings.webp',
        title: 'Ardlings',
        description: 'Ardlings are celestial beings with animal-like heads, representing divine attributes tied to their forms. Whether owl-headed for wisdom or wolf-headed for ferocity, Ardlings embody celestial virtues. They are often clerics or paladins, serving as agents of divine forces. Their unique appearances and celestial origins make them symbols of hope and guidance in their worlds.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/owlin.webp',
        title: 'Owlin (Owlfolk)',
        description: 'Owlin are owl-like humanoids with an affinity for knowledge and quiet observation. They are stealthy and wise, often excelling as rangers or wizards. Their ability to fly silently gives them an edge in exploration and combat. Owlin often act as scholars or scouts, blending their natural abilities with an inquisitive nature.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/ravenite_dragonborn.webp',
        title: 'Ravenite Dragonborn',
        description: 'Ravenite Dragonborn are a subrace of Dragonborn freed from servitude, known for their resilience and strong community bonds. Unlike other Dragonborn, Ravenites prioritize their kin and strive to overcome their oppressed past. They make excellent fighters or barbarians, channeling their innate strength into defending their newfound freedom.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/revenant.webp',
        title: 'Revenant',
        description: 'Revenants are undead beings driven by a singular purpose—usually revenge or redemption. Their persistence and determination make them unyielding adventurers. Revenants often excel as fighters or warlocks, using their supernatural endurance and grim resolve to achieve their goals. Despite their undead nature, they retain fragments of their past humanity.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/chromatic_dragonborn.webp',
        title: 'Chromatic Dragonborn',
        description: 'Chromatic Dragonborn are tied to the elemental powers of chromatic dragons, such as fire, ice, and lightning. Their vibrant scales reflect their draconic ancestry, granting them resistance to their associated elements. Chromatic Dragonborn excel as sorcerers or fighters, blending their innate magic with martial skill.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/metallic_dragonborn.webp',
        title: 'Metallic Dragonborn',
        description: 'Metallic Dragonborn are noble and virtuous, reflecting the traits of metallic dragons like gold and silver. They possess breath weapons and resistances aligned with their draconic heritage. Metallic Dragonborn often thrive as paladins or clerics, guided by a strong moral compass and a desire to protect others.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/gem_dragonborn.webp',
        title: 'Gem Dragonborn',
        description: 'Gem Dragonborn are rare and mystical, reflecting the power of gem dragons such as amethyst or sapphire. They possess psychic abilities and elemental resistances tied to their gemstone lineage. Gem Dragonborn excel as sorcerers or wizards, harnessing their innate magic to shape reality.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/illithid_tadpole.webp',
        title: 'Illithid Tadpole (Playable Mind Flayer)',
        description: 'Illithid Tadpoles are the earliest stage of Mind Flayers, possessing both their monstrous potential and a spark of individuality. Playable Illithid Tadpoles struggle to balance their identity with their parasitic nature. They often excel as psionic sorcerers or warlocks, wielding mind-affecting abilities in unique ways.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/dhampir.webp',
        title: 'Dhampir (Half-Vampire)',
        description: 'Dhampirs are caught between life and undeath, inheriting traits from their vampire ancestry. They possess heightened senses, charm, and agility but are often haunted by a thirst for blood. Dhampirs excel as rogues or warlocks, embracing their dark nature to become powerful adventurers.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/hexblood.webp',
        title: 'Hexblood (Cursed Fey)',
        description: 'Hexbloods are individuals touched by fey magic or cursed by witches. They possess mystical abilities and often exhibit otherworldly features such as horns or colorful skin. Hexbloods thrive as warlocks or sorcerers, using their unique talents to navigate the mortal and fey realms.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/reborn.webp',
        title: 'Reborn (Undead-like)',
        description: 'Reborn are individuals who have returned from death, retaining fragments of their previous lives. They possess resilience and a unique perspective on existence. Reborn excel as fighters or wizards, using their undead fortitude and knowledge to face new challenges.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/lycanthrope.webp',
        title: 'Lycanthrope (Werewolf/Wererat/Weretiger, etc.)',
        description: 'Lycanthropes are humanoids cursed or blessed with the ability to transform into beasts. Their dual nature grants them enhanced strength, senses, and combat abilities. Lycanthropes are fierce warriors, often excelling as barbarians or rangers. They must grapple with their primal instincts while protecting their allies.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/vampire_spawn.webp',
        title: 'Vampire Spawn',
        description: 'Vampire Spawn are lesser vampires bound to their creators will but capable of breaking free. They possess enhanced strength, speed, and charm, making them formidable adversaries or allies. Vampire Spawn often excel as rogues or warlocks, using their supernatural abilities to manipulate and overpower enemies.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/merfolk.webp',
        title: 'Merfolk',
        description: 'Merfolk are aquatic humanoids who thrive in underwater kingdoms or coastal regions. They possess natural swimming abilities and an affinity for water magic. Merfolk excel as druids or rangers, using their connection to the sea to protect their homes and allies.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/living_construct.webp',
        title: 'Living Construct',
        description: 'Living Constructs are artificial beings imbued with sentience, often created for labor or war. They possess immense durability and adaptability, excelling as fighters or artificers. Living Constructs struggle with questions of purpose and identity, striving to carve out a meaningful existence.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/gargoyle.webp',
        title: 'Gargoyle',
        description: 'Gargoyles are stone-like humanoids created as guardians. They possess immense strength and resilience, often serving as protectors of sacred sites. Gargoyles excel as fighters or paladins, using their durability and defensive nature to shield their allies.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/arachne.webp',
        title: 'Arachne (Spiderfolk)',
        description: 'Arachne are humanoid spiderfolk known for their cunning and agility. They often dwell in dark caves or dense forests, weaving webs to trap their enemies. Arachne excel as rogues or rangers, using their stealth and natural abilities to gain the upper hand in combat.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    },
    {
        image: 'races/phoenixborn.webp',
        title: 'Phoenixborn',
        description: 'Phoenixborn are humanoids blessed with the essence of a phoenix, granting them fiery abilities and the potential for rebirth. They possess radiant features and an innate connection to fire magic. Phoenixborn thrive as sorcerers or clerics, using their abilities to inspire hope and overcome challenges.',
        smtitle: '',
        smdescription: '',
        smtitle1: '',
        smdescription1: '',
        smtitle2: '',
        smdescription2: '',
        smtitle3: '',
        smdescription3: '',
    }
];

let currentraceIndex = 0;

const raceImage = document.getElementById('ImageBro');
const raceTitle = document.getElementById('Title');
const raceDescription = document.getElementById('Description');
const raceSMTitle = document.getElementById('SMTitle');
const raceSMDescription = document.getElementById('SMDescription');
const raceSMTitle1 = document.getElementById('SMTitle1');
const raceSMDescription1 = document.getElementById('SMDescription1');
const raceSMTitle2 = document.getElementById('SMTitle2');
const raceSMDescription2 = document.getElementById('SMDescription2');
const raceSMTitle3 = document.getElementById('SMTitle3');
const raceSMDescription3 = document.getElementById('SMDescription3');

document.getElementById('prevBtn').addEventListener('click', () => {
    currentraceIndex = (currentraceIndex - 1 + races.length) % races.length;
    updaterace();
});

document.getElementById('nextBtn').addEventListener('click', () => {
    currentraceIndex = (currentraceIndex + 1) % races.length;
    updaterace();
});

function updaterace() {
    const race = races[currentraceIndex];
    ImageBro.src = race.image;
    Title.textContent = race.title;
    Description.textContent = race.description;
    SMTitle.textContent = race.smtitle;
    SMDescription.textContent = race.smdescription;
    SMTitle1.textContent = race.smtitle1;
    SMDescription1.textContent = race.smdescription1;
    SMTitle2.textContent = race.smtitle2;
    SMDescription2.textContent = race.smdescription2;
    SMTitle3.textContent = race.smtitle3;
    SMDescription3.textContent = race.smdescription3;
}
